name: generate entree carto

on:
  workflow_run:
    workflows: ["refresh config_files"]
    types:
      - completed

jobs:
  refresh_config:
    runs-on: ubuntu-latest
    environment: qualification
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 #install the python needed
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: execute py script
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull --rebase
          python generator_entree_carto/entree_carto.py --input=dist/customConfig.json --output=entreeCarto.tmp 
          python extractor-thumbnails/thumbnails.py --input=entreeCarto.tmp --output=dist/entreeCarto.json
          git pull --rebase --autostash
          git add .
          git commit -m "generate entree carto"
          git push
      # Dépôt sur s3
      - name: Decrypt rclone conf
        run: ./scripts/decrypt_secret.sh
        env:
          RCLONE_PASSPHRASE: ${{ secrets.RCLONE_PASSPHRASE }}
          S3_CONF_FILENAME: ${{ secrets.S3_CONF_FILENAME }}
          S3_PATH: ${{ secrets.S3_PATH }}
      - name: Install rclone
        run: apt-get update && apt-get install rclone
      - name: Transfert configuration sur S3
        run: bash ./scripts/copy_entree_carto_conf_s3.sh

